#!/usr/bin/env python3
"""Build editing-only media with ffmpeg. Originals remain the export sources."""
import concurrent.futures
import hashlib
import json
import struct
import subprocess
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'assets/editor-previews'
LIMIT = 960

def transcode(source, target, limit, video=False):
    args = ['ffmpeg', '-v', 'error', '-y', '-i', str(source)]
    if video:
        args += ['-an', '-vf', 'scale=360:640:force_original_aspect_ratio=decrease,fps=30', '-c:v', 'libx264', '-crf', '27', '-preset', 'fast', '-pix_fmt', 'yuv420p', '-movflags', '+faststart']
    else:
        args += ['-vf', f'scale={limit}:{limit}:force_original_aspect_ratio=decrease', '-frames:v', '1']

    if target.suffix == '.webp':
        with tempfile.TemporaryDirectory(prefix='smm-photo-') as folder:
            png = Path(folder) / 'photo.png'
            subprocess.run(args + [str(png)], check=True)
            subprocess.run(['cwebp', '-quiet', '-q', '76', str(png), '-o', str(target)], check=True)
    else:
        subprocess.run(args + [str(target)], check=True)

def compact_glb(source, target):
    data = source.read_bytes()
    size = struct.unpack_from('<I', data, 12)[0]
    doc = json.loads(data[20:20 + size])
    binary = data[28 + size:]
    assert len(doc['buffers']) == 1 and 'uri' not in doc['buffers'][0]
    images = {image['bufferView']: image for image in doc.get('images', [])}
    packed = bytearray()
    with tempfile.TemporaryDirectory(prefix='smm-textures-') as folder:
        folder = Path(folder)
        for index, view in enumerate(doc['bufferViews']):
            start = view.get('byteOffset', 0)
            chunk = binary[start:start + view['byteLength']]
            if index in images:
                raw, small = folder / f'{index}.image', folder / f'{index}.png'
                raw.write_bytes(chunk)
                transcode(raw, small, 512)
                chunk = small.read_bytes()
                images[index]['mimeType'] = 'image/png'
            packed.extend(b'\0' * (-len(packed) % 4))
            view['byteOffset'], view['byteLength'] = len(packed), len(chunk)
            packed.extend(chunk)
    doc['buffers'][0]['byteLength'] = len(packed)
    encoded = json.dumps(doc, separators=(',', ':')).encode()
    encoded += b' ' * (-len(encoded) % 4)
    packed.extend(b'\0' * (-len(packed) % 4))
    target.write_bytes(struct.pack('<III', 0x46546c67, 2, 28 + len(encoded) + len(packed)) + struct.pack('<II', len(encoded), 0x4e4f534a) + encoded + struct.pack('<II', len(packed), 0x004e4942) + packed)

def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    products = json.loads((ROOT / 'assets/album-v2/products.json').read_text())
    sources = {p['glb'] for p in products}
    for product in products:
        sources.update('../' + str((Path('assets/album-v2') / photo['file'])) for photo in product['photos'])
        sources.update('../' + str((Path('assets/album-v2') / file)) for file in product['lineup'].values())
    sources.add('../assets/album-v2/intro-winter.mp4')
    def build(key):
        remote = key.startswith('https:')
        source = None if remote else (ROOT / key[3:]).resolve()
        key = key if remote else '../' + source.relative_to(ROOT).as_posix()
        suffix = '.glb' if remote else source.suffix
        filename = hashlib.sha256(key.encode()).hexdigest()[:16] + suffix
        target = OUTPUT / filename
        with tempfile.TemporaryDirectory(prefix='smm-source-') as folder:
            if remote:
                source = Path(folder) / 'source.glb'
                with urllib.request.urlopen(key, timeout=120) as response: source.write_bytes(response.read())
            if suffix == '.glb': compact_glb(source, target)
            else: transcode(source, target, LIMIT, suffix == '.mp4')
            return key, '../assets/editor-previews/' + filename, source.stat().st_size, target.stat().st_size
    with concurrent.futures.ThreadPoolExecutor(max_workers=3) as pool:
        results = sorted(pool.map(build, sorted(sources)))
    mapping = {key: value for key, value, _, _ in results}
    (ROOT / 'lib/editor-preview-assets.js').write_text('// Generated by scripts/build-editor-previews.py. Editing copies only.\nexport const EDITOR_PREVIEWS = ' + json.dumps(mapping, indent=2) + ';\n')
    print(json.dumps({'files':len(results), 'originalBytes':sum(r[2] for r in results), 'previewBytes':sum(r[3] for r in results)}, indent=2))
    for key, _, original, preview in results:
        print(f'{original:>10} -> {preview:>8} {key}')

if __name__ == '__main__': main()
